### ISSUE TITLE
Pysnip doesn't start with latest twisted version (15.0.0)

### ISSUE THREAD

**Issue by noway421** [NateShoffner/PySnip#2]
```
(creating config.txt from config.txt.default)
('from' command disabled - missing pygeoip)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "run.py", line 649, in __init__
    self.ban_manager = bansubscribe.BanManager(self, ban_subscribe)
  File "/home/archie/PySnip-master/feature_server/bansubscribe.py", line 37, in __init__
    self.loop.start(UPDATE_INTERVAL, now = True)
  File "/home/archie/PySnip-master/venv/lib/python2.7/site-packages/twisted/internet/task.py", line 173, in start
    self()
  File "/home/archie/PySnip-master/venv/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/archie/PySnip-master/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
    result = f(*args, **kw)
  File "/home/archie/PySnip-master/feature_server/bansubscribe.py", line 43, in update_bans
    defers.append(self.protocol.getPage(url).addCallback(self.got_bans,
  File "run.py", line 1005, in getPage
    bindAddress = (self.config.get('network_interface', ''), 0), **kw)
  File "../pyspades/web.py", line 12, in getPage
    from twisted.web.client import _URI
exceptions.ImportError: cannot import name _URI
2015-04-11 22:08:47+1200 [-] Log opened.
2015-04-11 22:08:47+1200 [-] Generating map 'classicgen #1009314409'...
2015-04-11 22:08:51+1200 [-] Map loaded successfully.
2015-04-11 22:08:51+1200 [-] Traceback (most recent call last):
2015-04-11 22:08:51+1200 [-]   File "run.py", line 1061, in <module>
2015-04-11 22:08:51+1200 [-]     protocol_instance = protocol_class(interface, config)
2015-04-11 22:08:51+1200 [-]   File "./scripts/disco.py", line 39, in __init__
2015-04-11 22:08:51+1200 [-]     protocol.__init__(self, *arg, **kw)
2015-04-11 22:08:51+1200 [-]   File "run.py", line 689, in __init__
2015-04-11 22:08:51+1200 [-]     get_external_ip(config.get('network_interface', '')).addCallback(
2015-04-11 22:08:51+1200 [-]   File "../pyspades/master.py", line 108, in get_external_ip
2015-04-11 22:08:51+1200 [-]     return getPage(IP_GETTER, bindAddress = (interface, 0))
2015-04-11 22:08:51+1200 [-]   File "../pyspades/web.py", line 12, in getPage
2015-04-11 22:08:51+1200 [-]     from twisted.web.client import _URI
2015-04-11 22:08:51+1200 [-] ImportError: cannot import name _URI
```
However, pysnip known to work with 14.0.2 version.

**Comment by NateShoffner** [comment]
Fixed in https://github.com/NateShoffner/PySnip/commit/8868081bccb78970b217d7fd907af9d810175291

Twisted really needs to just pick a convention and stick with it.
